spring:
  mvc:
    static-path-pattern: /static/** # 解决 thymeleaf 静态资源访问失败的问题
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/cloud_disk?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT
    driver-class-name: com.mysql.cj.jdbc.Driver


  # thymeleaf配置
  thymeleaf:
    cache: false
    encoding: UTF-8
    mode: HTML
    prefix: classpath:/templates
    suffix: .html
    check-template-location: true

# 服务端口
server:
  port: 8080

# 配置mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    #lazy-loading-enabled: true
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl